% Simscape(TM) Multibody(TM) version: 24.2

% This is a model data file derived from a Simscape Multibody Import XML file using the smimport function.
% The data in this file sets the block parameter values in an imported Simscape Multibody model.
% For more information on this file, see the smimport function help page in the Simscape Multibody documentation.
% You can modify numerical values, but avoid any other changes to this file.
% Do not add code to this file. Do not edit the physical units shown in comments.

%%%VariableName:smiData


%============= RigidTransform =============%

%Initialize the RigidTransform structure array by filling in null values.
% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Apr-2025 17:01:36
%  MATLAB version: 24.2.0.2712019 (R2024b)
% -------------------------------------------------------------------
                                         

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [0 6.35 0];
smiData.RigidTransform(1).angle = 2.0943951023931953;
smiData.RigidTransform(1).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  -0.57735026918962584];
smiData.RigidTransform(1).ID = 'B[basePlate-1:-:wallBase-1]';
smiData.RigidTransform(1).ID = convertCharsToStrings( ...
  smiData.RigidTransform(1).ID);
smiData.RigidTransform(2).translation = ...
  [71.846109286656755 0 -12.5];
smiData.RigidTransform(2).angle = 2.0943951023931953;
smiData.RigidTransform(2).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  -0.57735026918962584];
smiData.RigidTransform(2).ID = 'F[basePlate-1:-:wallBase-1]';
smiData.RigidTransform(2).ID = convertCharsToStrings( ...
  smiData.RigidTransform(2).ID);
smiData.RigidTransform(3).translation = ...
  [0 4.4999999999999991 15];
smiData.RigidTransform(3).angle = 2.0943951023931953;
smiData.RigidTransform(3).axis = [0.57735026918962584 0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(3).ID = 'B[wall-1:-:wallBase-1]';
smiData.RigidTransform(3).ID = convertCharsToStrings( ...
  smiData.RigidTransform(3).ID);
smiData.RigidTransform(4).translation = ...
  [9.5249999999999986 4.4999999999999982 15];
smiData.RigidTransform(4).angle = 2.0943951023931953;
smiData.RigidTransform(4).axis = [0.57735026918962584 0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(4).ID = 'F[wall-1:-:wallBase-1]';
smiData.RigidTransform(4).ID = convertCharsToStrings( ...
  smiData.RigidTransform(4).ID);
smiData.RigidTransform(5).translation = ...
  [0 0 90];
smiData.RigidTransform(5).angle = 3.1415926535897931;
smiData.RigidTransform(5).axis = [1 0 0];
smiData.RigidTransform(5).ID = 'B[motorRod-1:-:pendulum-1]';
smiData.RigidTransform(5).ID = convertCharsToStrings( ...
  smiData.RigidTransform(5).ID);
smiData.RigidTransform(6).translation = ...
  [-25.4 -3.5527136788005009E-15 7.7000000000000171];
smiData.RigidTransform(6).angle = 3.1415926535897931;
smiData.RigidTransform(6).axis = [0.70710678118654746 0.70710678118654757 ...
                                  0];
smiData.RigidTransform(6).ID = 'F[motorRod-1:-:pendulum-1]';
smiData.RigidTransform(6).ID = convertCharsToStrings( ...
  smiData.RigidTransform(6).ID);
smiData.RigidTransform(7).translation = ...
  [0 0 75];
smiData.RigidTransform(7).angle = 3.1415926535897931;
smiData.RigidTransform(7).axis = [1 0 0];
smiData.RigidTransform(7).ID = 'B[motorModel-1:-:motorRod-1]';
smiData.RigidTransform(7).ID = convertCharsToStrings( ...
  smiData.RigidTransform(7).ID);
smiData.RigidTransform(8).translation = ...
  [0 0 69.999999999999986];
smiData.RigidTransform(8).angle = 3.1415926535897931;
smiData.RigidTransform(8).axis = [1 0 0];
smiData.RigidTransform(8).ID = 'F[motorModel-1:-:motorRod-1]';
smiData.RigidTransform(8).ID = convertCharsToStrings( ...
  smiData.RigidTransform(8).ID);
smiData.RigidTransform(9).translation = ...
  [0 6.35 0];
smiData.RigidTransform(9).angle = 2.0943951023931953;
smiData.RigidTransform(9).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  -0.57735026918962584];
smiData.RigidTransform(9).ID = 'B[basePlate-1:-:motorHolder-1]';
smiData.RigidTransform(9).ID = convertCharsToStrings( ...
  smiData.RigidTransform(9).ID);
smiData.RigidTransform(10).translation = ...
  [12.500000000000018 -70 37.500000000000028];
smiData.RigidTransform(10).angle = 2.0943951023931953;
smiData.RigidTransform(10).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(10).ID = 'F[basePlate-1:-:motorHolder-1]';
smiData.RigidTransform(10).ID = convertCharsToStrings( ...
  smiData.RigidTransform(10).ID);
smiData.RigidTransform(11).translation = ...
  [0 0 75];
smiData.RigidTransform(11).angle = 0;
smiData.RigidTransform(11).axis = [0 0 0];
smiData.RigidTransform(11).ID = 'B[motorModel-1:-:motorHolder-1]';
smiData.RigidTransform(11).ID = convertCharsToStrings( ...
  smiData.RigidTransform(11).ID);
smiData.RigidTransform(12).translation = ...
  [-7.1054273576010019E-15 0 35.000000000000014];
smiData.RigidTransform(12).angle = 0;
smiData.RigidTransform(12).axis = [0 0 0];
smiData.RigidTransform(12).ID = 'F[motorModel-1:-:motorHolder-1]';
smiData.RigidTransform(12).ID = convertCharsToStrings( ...
  smiData.RigidTransform(12).ID);
smiData.RigidTransform(13).translation = ...
  [0 0 0];
smiData.RigidTransform(13).angle = 0;
smiData.RigidTransform(13).axis = [0 0 0];
smiData.RigidTransform(13).ID = 'RootGround[basePlate-1]';
smiData.RigidTransform(13).ID = convertCharsToStrings( ...
  smiData.RigidTransform(13).ID);
smiData.Solid = struct;
smiData.Solid(1).mass = 0.063838687006731051;
smiData.Solid(1).CoM = [-19.960154364912189 4.7638107023203879 0];
smiData.Solid(1).MoI = [22.179651481506728 30.239028144878954 9.0291647161138684 ...
                        ];
smiData.Solid(1).PoI = [0 0 -0.0012402857469648049];
smiData.Solid(1).color = [0.89803921568627454 0.91764705882352937 0.92941176470588238 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'wallBase*:*Default';
smiData.Solid(1).ID = convertCharsToStrings(smiData.Solid(1).ID);
smiData.Solid(2).mass = 0.05204602344232824;
smiData.Solid(2).CoM = [0 -32.295221818593419 0];
smiData.Solid(2).MoI = [52.709940035909952 14.315232580509493 53.195061084607332 ...
                        ];
smiData.Solid(2).PoI = [0 0 0];
smiData.Solid(2).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'motorHolder*:*Default';
smiData.Solid(2).ID = convertCharsToStrings(smiData.Solid(2).ID);
smiData.Solid(3).mass = 0.039492175850113873;
smiData.Solid(3).CoM = [0 0 37.5];
smiData.Solid(3).MoI = [20.245762680000507 20.245762680000507 3.4676105005192475 ...
                        ];
smiData.Solid(3).PoI = [0 0 0];
smiData.Solid(3).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'motorModel*:*Default';
smiData.Solid(3).ID = convertCharsToStrings(smiData.Solid(3).ID);
smiData.Solid(4).mass = 0.13623072420427693;
smiData.Solid(4).CoM = [0 3.1750000000000003 0];
smiData.Solid(4).MoI = [149.95832870221744 557.88526216423918 408.84246069147622 ...
                        ];
smiData.Solid(4).PoI = [0 0 0];
smiData.Solid(4).color = [0 0 0];
smiData.Solid(4).opacity = 0;
smiData.Solid(4).ID = 'basePlate*:*Default';
smiData.Solid(4).ID = convertCharsToStrings(smiData.Solid(4).ID);
smiData.Solid(5).mass = 0.12189709037753729;
smiData.Solid(5).CoM = [-4.7625000000000011 37.657695407099013 0];
smiData.Solid(5).MoI = [97.79851405458956 41.945706079415856 57.696006260204285 ...
                        ];
smiData.Solid(5).PoI = [0 0 0];
smiData.Solid(5).color = [0.89803921568627454 0.91764705882352937 0.92941176470588238 ...
                          ];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'wall*:*Default';
smiData.Solid(5).ID = convertCharsToStrings(smiData.Solid(5).ID);
smiData.Solid(6).mass = 0.039369999999999995;
smiData.Solid(6).CoM = [3.9890291234574512E-7 -0.031421029560594761 -2.7853128131815159E-7 ...
                        ];
smiData.Solid(6).MoI = [1.6099603058895022 20.225679340313885 21.2];
smiData.Solid(6).PoI = [0 0 0];
smiData.Solid(6).color = [0.89803921568627454 0.91764705882352937 0.92941176470588238 ...
                          ];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'pendulum*:*Default';
smiData.Solid(6).ID = convertCharsToStrings(smiData.Solid(6).ID);
smiData.Solid(7).mass = 0.0087084948357509049;
smiData.Solid(7).CoM = [0 0 45.000000000000007];
smiData.Solid(7).MoI = [5.8869425089676062 5.8869425089676062 1.6700000000000002 ...
                        ];
smiData.Solid(7).PoI = [0 0 0];
smiData.Solid(7).color = [0.77647058823529413 0.75686274509803919 0.73725490196078436 ...
                          ];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'motorRod*:*Default';
smiData.Solid(7).ID = convertCharsToStrings(smiData.Solid(7).ID);
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint.Rz = struct;
smiData.RevoluteJoint.Rz.Pos = 0;
smiData.RevoluteJoint.ID = '[motorModel-1:-:motorRod-1]';
smiData.RevoluteJoint.ID = convertCharsToStrings( ...
  smiData.RevoluteJoint.ID);

